### ISSUE TITLE
How to visualize the structure map

### ISSUE THREAD

**Issue by kunkun0w0** [lyndonzheng/F-LSeSim#3]
Hi~
It is a wonderful job. ^_^
And I am curious how to visualize the structure map like figure 1 in the paper.
Can you release the relevant code?

**Comment by Lucky0775** [comment]
> Hi~ It is a wonderful job. ^_^ And I am curious how to visualize the structure map like figure 1 in the paper. Can you release the relevant code?

Hello, have you solved this problem?  Can you tell me how you visualized the structure map?  All the best!
