### ISSUE TITLE
How to get D&C score

### ISSUE THREAD

**Issue by ygjwd12345** [lyndonzheng/F-LSeSim#4]
According to "Similar to LPIPS, we first sampled 19 pairs for each image and then used the code at https://github.com/mseitzer/pytorch-fid to extract the features of real and generated images. Finally, we fed these 1900 generated samples and real features with 2048-dimensions to the PRDC function provided in https://github.com/clovaai/generative-evaluation-prdc to calculate these scores."
So will you run 19times to generate enough generated samples?

**Comment by lyndonzheng** [comment]
Hi @ygjwd12345 thanks for your interest. We sampled 19 times for two purposes: 1. The D&C score is sensitive to image numbers in our setting, so we sampled multiple times; 2. We would like to make sure these scores (LPIPS for _diversity_ and D&C for _fidelity_ and _diversity_) come from the same tested results.

**Comment by ygjwd12345** [comment]
Would you mind to tell me how to sample 19 times?

**Comment by ygjwd12345** [comment]
Meanwhile, LPIPS should be smaller is better according to the original paper(The Unreasonable Effectiveness of Deep Features as a Perceptual Metric) and official GitHub(https://github.com/richzhang/PerceptualSimilarity). And I wonder how real images measure LPIPS FID and D&C.

**Comment by ygjwd12345** [comment]
> Hi @ygjwd12345 thanks for your interest. We sampled 19 times for two purposes: 1. The D&C score is sensitive to image numbers in our setting, so we sampled multiple times; 2. We would like to make sure these scores (LPIPS for _diversity_ and D&C for _fidelity_ and _diversity_) come from the same tested results.

If there are more than 100 images, how to sample them? why not you test all images directly?

**Comment by lyndonzheng** [comment]
> Meanwhile, LPIPS should be smaller is better according to the original paper(The Unreasonable Effectiveness of Deep Features as a Perceptual Metric) and official GitHub(https://github.com/richzhang/PerceptualSimilarity). And I wonder how real images measure LPIPS FID and D&C.

Please refer to the paper [BicycleGAN](https://papers.nips.cc/paper/2017/file/819f46e52c25763a55cc642422644317-Paper.pdf), where the LPIPS is used to evaluate the diversity of the results. The larger score means larger difference between the generated results.

**Comment by lyndonzheng** [comment]
> Would you mind to tell me how to sample 19 times?

Please refer to the [BicycleGAN](https://papers.nips.cc/paper/2017/file/819f46e52c25763a55cc642422644317-Paper.pdf) and [MUNIT](https://openaccess.thecvf.com/content_ECCV_2018/papers/Xun_Huang_Multimodal_Unsupervised_Image-to-image_ECCV_2018_paper.pdf) to get multiple and diverse results.

**Comment by ygjwd12345** [comment]
> > Would you mind to tell me how to sample 19 times?
> 
> Please refer to the [BicycleGAN](https://papers.nips.cc/paper/2017/file/819f46e52c25763a55cc642422644317-Paper.pdf) and [MUNIT](https://openaccess.thecvf.com/content_ECCV_2018/papers/Xun_Huang_Multimodal_Unsupervised_Image-to-image_ECCV_2018_paper.pdf) to get multiple and diverse results.

However, there is no get_z_random in your code.  "sh ./scripts/test_fid.sh" can not realise it.
