### ISSUE TITLE
Question about sc_model.py (bs_per_gpu)

### ISSUE THREAD

**Issue by 1211sh** [lyndonzheng/F-LSeSim#6]
![image](https://user-images.githubusercontent.com/33894603/132533451-d30d0ad9-22ff-4335-bdbf-8b2ea5da18c7.png)

Hi,
I am wondering how the multi-gpu process works in the line 102 and 103.
Line 102 : self.real_A = self.real_A[:bs_per_gpu]

I think self.real_A[:bs_per_gpu] is just simply removing a part of self.real_A, not working as spliting data for multi-gpu.

Is it a typo? or am I wrong?

**Comment by o0t1ng0o** [comment]
@1211sh 
I think that row 102-103 can be deleted?

**Comment by lyndonzheng** [comment]
Hi @1211sh, this code is used for initializing the feature extractor networks and auxiliary optimizers, instead of the multi-gpu training. The code is based on the [CUT](https://github.com/taesungp/contrastive-unpaired-translation/blob/master/models/cut_model.py).
