### ISSUE TITLE
Evaluation of Cityscapes

### ISSUE THREAD

**Issue by fnzhan** [lyndonzheng/F-LSeSim#8]
Thanks for the great work! 
In the paper, you claim using the pre-trained drn model to conduct the evaluation, while CUT claim they trained a model with drn-d-22 structure to conduct the evaluation. 
I want to know which model is adopted in your paper to evaluate the performance? drn-d-22.pth or drn-d-105-ms.pth?
I tested the pre-trained drn-d-22.pth model and cannot reproduce the results of CUT, but drn-d-105-ms.pth can match the reported results of CUT. @lyndonzheng

**Comment by dmadsen100** [comment]
Similar question, I also cannot reproduce the mAP reported in CUT. CUT adopt the pre-trained model drn-d-22.pth to conduct evaluation, do you also use the same pretrained model to evaluate the pixAcc? And how about the mAP score of your model? @lyndonzheng  Looking forward to your response.

**Comment by dmadsen100** [comment]
For LSeSim, I also cannot reproduce the reported FID of 49.7. I train the model several times with the default setting of LSeSim (with --learned_attn and --augment), but only get FID between 62-64, much lower than the reported results.

**Comment by Lucky0775** [comment]
> 

Hi,Did you solve this problem? I also get the FID about 60,it is lower than the reported results.
